// generated by Gemini

#include <Arduino.h>

// --- 設定エリア ---
#define MODEM_TX_PIN 0
#define MODEM_RX_PIN 1
#define MODEM_BAUD 115200
#define BUTTON_PIN 15

// 送信間隔 (30秒)
#define SEND_INTERVAL 30000

// グローバル変数
bool DEBUG = true;
bool SORACOM_CONNECTED = false;
bool MQTT_CONNECTED = false;
unsigned long lastSendTime = 0;

// 緯度経度保持用
float lat = 0.0;
float lng = 0.0;

// ハードウェアシリアル
UART SerialModem(MODEM_TX_PIN, MODEM_RX_PIN, NC, NC);

// --- ユーティリティ ---

void log(String str) { Serial.print(str); }

void debug(String str) {
    if (DEBUG) Serial.println(str);
}

void sendMsg(String cmd) {
    while (SerialModem.available()) SerialModem.read();
    SerialModem.print(cmd);
}

String waitMsg(unsigned long timeout) {
    String response = "";
    unsigned long start = millis();
    while (millis() - start < timeout) {
        if (SerialModem.available()) {
            char c = SerialModem.read();
            response += c;
        }
    }
    return response;
}

String send_and_getMsg(String cmd) {
    sendMsg(cmd);
    return waitMsg(1000);
}

// --- データ処理 ---

// 文字列解析ヘルパー
String getValue(String data, char separator, int index) {
    int found = 0;
    int strIndex[] = {0, -1};
    int maxIndex = data.length() - 1;

    for (int i = 0; i <= maxIndex && found <= index; i++) {
        if (data.charAt(i) == separator || i == maxIndex) {
            found++;
            strIndex[0] = strIndex[1] + 1;
            strIndex[1] = (i == maxIndex) ? i + 1 : i;
        }
    }
    return found > index ? data.substring(strIndex[0], strIndex[1]) : "";
}

// GNSS情報を更新
void updateGnssData() {
    sendMsg("AT+CGNSINF\r\n");
    String res = waitMsg(1000);

    if (res.indexOf("+CGNSINF:") != -1) {
        int start = res.indexOf("+CGNSINF:");
        String cleanRes = res.substring(start);

        String latStr = getValue(cleanRes, ',', 3);
        String lngStr = getValue(cleanRes, ',', 4);

        if (latStr.length() > 0 && lngStr.length() > 0) {
            lat = latStr.toFloat();
            lng = lngStr.toFloat();
        }
    }
}

// SORACOM接続
void connectSoracom() {
    log("Connecting to SORACOM...\r\n");
    send_and_getMsg("AT+CGDCONT=1,\"IP\",\"soracom.io\"\r\n");
    send_and_getMsg("AT+CNACT=0,1\r\n");
    delay(2000);

    String res = send_and_getMsg("AT+CNACT?\r\n");
    if (res.indexOf(",1,\"") != -1) {
        SORACOM_CONNECTED = true;
        log("Network Connected.\r\n");
    } else {
        log("Retry Network...\r\n");
    }
}

// MQTT接続
void connectMqtt() {
    log("Connecting to MQTT...\r\n");
    send_and_getMsg("AT+SMCONF=\"URL\",\"broker.emqx.io\",\"1883\"\r\n");
    send_and_getMsg("AT+SMCONF=\"CLEANSS\",1\r\n");
    send_and_getMsg("AT+SMCONF=\"CLIENTID\",\"pico_csv_sender\"\r\n");

    String res = send_and_getMsg("AT+SMCONN\r\n");
    if (res.indexOf("OK") != -1) {
        MQTT_CONNECTED = true;
        log("MQTT Connected.\r\n");
    }
}

// --- メイン処理 ---

void setup() {
    Serial.begin(115200);
    SerialModem.setTX(MODEM_TX_PIN);
    SerialModem.setRX(MODEM_RX_PIN);
    SerialModem.begin(MODEM_BAUD);

    pinMode(BUTTON_PIN, INPUT_PULLUP);

    delay(3000);
    log("System Start (CSV Mode).\r\n");

    send_and_getMsg("AT+CREBOOT\r\n");
    delay(5000);

    log("Powering ON GNSS...\r\n");
    send_and_getMsg("AT+CGNSPWR=1\r\n");
    delay(2000);
}

void loop() {
    if (!SORACOM_CONNECTED) connectSoracom();
    if (SORACOM_CONNECTED && !MQTT_CONNECTED) connectMqtt();

    if (millis() - lastSendTime > SEND_INTERVAL) {
        lastSendTime = millis();

        if (MQTT_CONNECTED) {
            // 1. GNSS情報更新
            updateGnssData();

            // 2. CSVペイロード作成
            // 例: "35.689500,139.691700"
            String payload = String(lat, 6) + "," + String(lng, 6);

            log("Sending: " + payload + "\r\n");


            uint8_t payload[8];

            int32_t lat_int = (int32_t)(lat * 1000000);
            int32_t lng_int = (int32_t)(lng * 1000000);

            memcpy($payload[0], &lat_int, 4);
            memcpy($payload[4], &lng_int, 4);

            // 3. 送信
            String header = String("AT+SMPUB=\"pub_topic\",") + String(8) + ",0,1\r\n";
            sendMsg(header);
            // delay(100);
            // sendMsg(payload + "\r\n");

            SerialAT.write(payload, 8)

            // 結果読み捨て
            waitMsg(1000);
        }
    }
    delay(10);
}

/*
# payload = b'35.689500,139.691700'
data_str = payload.decode('utf-8')
parts = data_str.split(',')

if len(parts) == 2:
    lat = float(parts[0])
    lng = float(parts[1])
    print(f"Latitude: {lat}, Longitude: {lng}")
*/